config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :statuses

   root 'statuses#home'

   post '/comment_create', to: 'statuses#create_comment', as: :comment_create

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  def home
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = current_user.statuses.new
    @statuses = Status.order(:created_at) 
    @comments = @status.comments
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @user = current_user
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to :back, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_comment
   @status = Status.find(params[:comment][:status_id])
   @user = @status.user
   @comment = current_user.comments.new
   @comment.comment = params[:comment][:comment]
   @comment.commentable = @status 
   @comment.save
   @comments = @status.comments

   redirect_to new_status_path(@status)
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:status)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_comment.html.slim
.container
  .row
    .col-md-12
    = simple_form_for(:comment, url: comment_create_path)  do |f|
     .form-group
       = f.input :comment, placeholder: "Writte a some comment...", input_html: { class: 'form-control' }
       = f.hidden_field :status_id, value: status
      
     = f.submit "Submit", class: "btn btn-success"

app/views/statuses/_form.html.slim
.container
  .row
    = image_tag current_user.image.thumb.url, class: "image img-circle" 
    .col-sm-8
      = simple_form_for @status do |f|
        = f.error_notification
        .form-group
          = f.input :status, input_html: { class: 'form-control' }
        br/
        = f.button :submit, class: "btn3d btn btn-primary btn-md", id: "myBtn"
        br/
        hr/
        - @statuses.each do |status|
          p
            .text-justify
              blockquote
                = status.status
            h2.comment_count= pluralize(@comments.count, "Comment")
            - @comments.each do |comment|
                .comment
                  p.comment= comment.comment
                  br/ 

            = render partial: "comment", locals: {status: status.id}  
            
       
          
        

app/views/statuses/edit.html.slim
h1 Editing status

== render 'form'

= link_to 'Show', @status
'|
= link_to 'Back', statuses_path

app/views/statuses/home.html.slim
.jumbotron
  .container
    h1 Nature
    p 
      |Breathtaking Nature Stock Photos for FREE!
    
    =link_to 'Click Here ', new_status_path, class: "btn btn-success btn-lg"

app/views/statuses/index.html.slim
h1 Listing statuses

table class= "table table-hover"
  thead
    tr
      th Status
      th
      th
      th

  tbody
    - @statuses.each do |status|
      tr
        td = status.status
        td = link_to 'Show', status
        td = link_to 'Edit', edit_status_path(status)
        td = link_to 'Destroy', status, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Status', new_status_path, class: "btn btn-default"

app/views/statuses/new.html.slim
== render 'form'

app/views/statuses/show.html.slim
p#notice = notice

p
  strong Status:
  = @status.status

= link_to 'Edit', edit_status_path(@status)
'|
= link_to 'Back', statuses_path